### ISSUE TITLE
Ambiguous search for OLS?

### ISSUE THREAD

**Issue by mastevb** [cthoyt/ols-client#3]
it seems like client.search only returns exact matches at this time?

**Comment by cthoyt** [comment]
Hi @mastevb, I haven't updated this package in a meaningful way since I wrote it for my master's work about 5 years ago, so it's likely the case that a few things weren't done so well (or the OLS API does something different now).

However, there is some renewed interest in re-writing this in a principled way to support the Ontology Access Kit (https://github.com/INCATools/ontology-access-kit), so there might be some movement soon, ideally with external help! Would be happy to accept a PR in the mean time - I am pretty quick to cut new releases too.

**Comment by cthoyt** [comment]
Hi @mastevb, the search function (https://ols-client.readthedocs.io/en/stable/cli.html#ols-client-search) now is fully configurable. Would be cool if you wanted to give some example usages that you could PR into the docs.
